package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/token"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"
)

var (
	name = flag.String("name", "", "name of the visitor type; must be set")

	typeNames = flag.String("type", "", "comma-separated list of type names; must be set")

	output = flag.String("output", "", "output file name; default srcdir/<type>_visitor.go")

	buildTags = flag.String("tags", "", "comma-separated list of build tags to apply")
)

func Usage() {
	fmt.Fprintf(os.Stderr, "Usage of %s:\n", os.Args[0])
	fmt.Fprint(os.Stderr, "\tvisitor [flags] -type T [directory]\n")

}

func main() {
	flag.Usage = Usage
	flag.Parse()

	if len(*typeNames) == 0 {
		flag.Usage()
		os.Exit(2)
	}
	types := strings.Split(*typeNames, ",")
	var tags []string
	if len(*buildTags) > 0 {
		panic("not implemented")
		// tags = strings.Split(*buildTags, ",")
	}

	args := flag.Args()
	if len(args) == 0 {
		// Default: process whole package in current directory.
		args = []string{"."}
	}

	var dir string
	if len(args) == 1 && isDirectory(args[0]) {
		dir = args[0]
	} else {
		if len(tags) != 0 {
			log.Fatal("-tags option applies only to directories, not when files are specified")
		}
		dir = filepath.Dir(args[0])
	}

	g := Generator{
		templateData: &templateData{
			PackageName: "", // Assign later.
			VisitorName: *name,
		},
	}
	g.parsePackage(args, tags)
	for _, typeName := range types {
		g.generate(typeName)
	}

	src := g.format()
	outputName := *output
	if outputName == "" {
		baseName := fmt.Sprintf("%s_visitor.go", *name)
		outputName = filepath.Join(dir, strings.ToLower(baseName))
	}
	err := os.WriteFile(outputName, src, 0644)
	if err != nil {
		log.Fatalf("writing output: %s", err)
	}
}

//#region -- Generator --

const TEMPLATE = `
// Code generated by "visitor"; DO NOT EDIT.
package {{.PackageName}}


type {{.VisitorName}}Visitor interface {
	{{range .Types}}
	visitFor{{.}}(t *{{.}})
	{{end}}
}

type Empty{{.VisitorName}}VisitorImpl struct{}
{{range .Types}}
func (v *Empty{{$.VisitorName}}VisitorImpl) visitFor{{.}}(t *{{.}}) {}

{{end}}

{{range .Types}}
func (t *{{.}}) accept(v {{$.VisitorName}}Visitor) {
	v.visitFor{{.}}(t)
}
{{end}}
`

type templateData struct {
	PackageName string
	VisitorName string
	Types       []string
}

type Generator struct {
	templateData *templateData
	pkg          *Package // Package we are scanning.
}

// File holds a single parsed file and associated data.

func (g *Generator) parsePackage(patterns []string, tags []string) {
	cfg := &packages.Config{
		Mode:       packages.NeedName | packages.NeedTypes | packages.NeedTypesInfo | packages.NeedSyntax,
		Tests:      false,
		BuildFlags: []string{fmt.Sprintf("-tags=%s", strings.Join(tags, " "))},
	}

	pkgs, err := packages.Load(cfg, patterns...)
	if err != nil {
		log.Fatal(err)
	}

	if len(pkgs) != 1 {
		log.Fatalf("expected 1 package; got %d", len(pkgs))
	}
	g.templateData.PackageName = pkgs[0].Name
	g.addPackage(pkgs[0])
}

func (g *Generator) addPackage(pkg *packages.Package) {
	g.pkg = &Package{
		name:  pkg.Name,
		defs:  pkg.TypesInfo.Defs,
		files: make([]*File, len(pkg.Syntax)),
	}

	for i, file := range pkg.Syntax {
		g.pkg.files[i] = &File{
			file: file,
			pkg:  g.pkg,
			// trimPrefix:  g.trimPrefix,
			// lineComment: g.lineComment,
		}
	}
}

func (g *Generator) generate(typeName string) {
	for _, file := range g.pkg.files {
		if file.file != nil {
			ast.Inspect(file.file, file.genDecl)
			for _, structTypeName := range file.structTypes {
				// In same package, structTypeName will be unique even if it is defined in different files.
				if typeName == structTypeName {
					g.templateData.Types = append(g.templateData.Types, typeName)
					break
				}
			}
		}
	}
}

func (g *Generator) format() []byte {
	builder := &strings.Builder{}
	template.Must(template.New("visitor").Parse(TEMPLATE)).Execute(builder, g.templateData)
	return []byte(builder.String())
}

type File struct {
	pkg  *Package  // Package to which this file belongs.
	file *ast.File // Parsed AST.
	// These fields are reset for each type being generated.
	// typeName string // Name of the constant type.
	structTypes []string // Names of the constant values.
	trimPrefix  string
	lineComment bool
}

func (f *File) genDecl(node ast.Node) bool {
	decl, ok := node.(*ast.GenDecl)

	if !ok || decl.Tok != token.TYPE {
		return true
	}
	typeName := decl.Specs[0].(*ast.TypeSpec).Name.Name
	f.structTypes = append(f.structTypes, typeName)

	return true
}

type Package struct {
	name  string
	defs  map[*ast.Ident]types.Object
	files []*File
}

//#endregion

// isDirectory reports whether the named file is a directory.
func isDirectory(name string) bool {
	info, err := os.Stat(name)
	if err != nil {
		log.Fatal(err)
	}
	return info.IsDir()
}
