// Code generated by "strategy"; DO NOT EDIT.
package examples


func (t StrategyType) NewDefaultStrategy() Strategy {
	var s Strategy
	switch t {
	case StrategyTypeAdd:
		s = &StrategyAdd{}
	case StrategyTypeSubtract:
		s = &StrategySubtract{}
	
	}
	return s
}

func (s StrategyAdd) GetStrategyType() StrategyType {
	return StrategyTypeAdd
}
	
func (s StrategySubtract) GetStrategyType() StrategyType {
	return StrategyTypeSubtract
}
	
func (t TravelStrategyType) NewDefaultStrategy() TravelStrategy {
	var s TravelStrategy
	switch t {
	case TravelStrategyTypeUber:
		s = &TravelStrategyUber{}
	case TravelStrategyTypeWalk:
		s = &TravelStrategyWalk{}
	}
	return s
}

func (s TravelStrategyUber) GetStrategyType() TravelStrategyType {
	return TravelStrategyTypeUber
}
	
func (s TravelStrategyWalk) GetStrategyType() TravelStrategyType {
	return TravelStrategyTypeWalk
}
	
