
// Code generated by "visitor"; DO NOT EDIT.
package examples


type TestVisitor interface {
	
	visitForTarget1(t *Target1)
	
	visitForTarget2(t *Target2)
	
}

type EmptyTestVisitorImpl struct{}

func (v *EmptyTestVisitorImpl) visitForTarget1(t *Target1) {}


func (v *EmptyTestVisitorImpl) visitForTarget2(t *Target2) {}




func (t *Target1) accept(v TestVisitor) {
	v.visitForTarget1(t)
}

func (t *Target2) accept(v TestVisitor) {
	v.visitForTarget2(t)
}

